/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as ReceiptsIdRouteImport } from './routes/receipts.$id'
import { Route as ApiPublicInboundReceiptsRouteImport } from './routes/api/public/inbound-receipts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const ReceiptsIdRoute = ReceiptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReceiptsRoute,
} as any)
const ApiPublicInboundReceiptsRoute =
  ApiPublicInboundReceiptsRouteImport.update({
    id: '/api/public/inbound-receipts',
    path: '/api/public/inbound-receipts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/inbound-receipts': typeof ApiPublicInboundReceiptsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/inbound-receipts': typeof ApiPublicInboundReceiptsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/receipts': typeof ReceiptsRouteWithChildren
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/receipts/$id': typeof ReceiptsIdRoute
  '/api/public/inbound-receipts': typeof ApiPublicInboundReceiptsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/projects'
    | '/receipts'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/projects/$id'
    | '/receipts/$id'
    | '/api/public/inbound-receipts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/projects'
    | '/receipts'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/projects/$id'
    | '/receipts/$id'
    | '/api/public/inbound-receipts'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/onboarding'
    | '/projects'
    | '/receipts'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/projects/$id'
    | '/receipts/$id'
    | '/api/public/inbound-receipts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReceiptsRoute: typeof ReceiptsRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicInboundReceiptsRoute: typeof ApiPublicInboundReceiptsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/receipts/$id': {
      id: '/receipts/$id'
      path: '/$id'
      fullPath: '/receipts/$id'
      preLoaderRoute: typeof ReceiptsIdRouteImport
      parentRoute: typeof ReceiptsRoute
    }
    '/api/public/inbound-receipts': {
      id: '/api/public/inbound-receipts'
      path: '/api/public/inbound-receipts'
      fullPath: '/api/public/inbound-receipts'
      preLoaderRoute: typeof ApiPublicInboundReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReceiptsRouteChildren {
  ReceiptsIdRoute: typeof ReceiptsIdRoute
}

const ReceiptsRouteChildren: ReceiptsRouteChildren = {
  ReceiptsIdRoute: ReceiptsIdRoute,
}

const ReceiptsRouteWithChildren = ReceiptsRoute._addFileChildren(
  ReceiptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReceiptsRoute: ReceiptsRouteWithChildren,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicInboundReceiptsRoute: ApiPublicInboundReceiptsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
